fix coverage

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,4 +1,5 @@
 name: Build, Test, Code Scan, and Auto Tag C# Project
+
 on:
   pull_request:
     branches:
@@ -37,12 +38,21 @@ jobs:
       - name: Convert coverage report to XML
         run: |
           reportgenerator -reports:**/coverage.cobertura.xml -targetdir:coverage/ -reporttypes:Cobertura
+          echo "Listing coverage directory contents:"
+          ls coverage/
 
-      # Store the build outputs as artifacts for the next job
-      - name: Upload build artifacts
+      - name: Check if coverage report exists
+        run: |
+          if [ ! -f coverage/coverage.cobertura.xml ]; then
+            echo "Coverage report not found!"
+            exit 1
+          fi
+
+      # Store the build outputs and coverage reports as artifacts for the next job
+      - name: Upload build artifacts and coverage reports
         uses: actions/upload-artifact@v3
         with:
-          name: build-artifacts
+          name: build-and-coverage-artifacts
           path: |
             **/*.dll
             **/*.pdb
@@ -55,10 +65,13 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v3
 
-      - name: Download build artifacts
+      - name: Download build and coverage artifacts
         uses: actions/download-artifact@v3
         with:
-          name: build-artifacts
+          name: build-and-coverage-artifacts
+
+      - name: List downloaded coverage files
+        run: ls coverage/
 
       # Run SonarCloud scan
       - name: SonarCloud Scan
@@ -71,7 +84,7 @@ jobs:
             -Dsonar.organization=artichand
             -Dsonar.host.url=https://sonarcloud.io
             -Dsonar.login=${{ secrets.SONAR_TOKEN }}
-            -Dsonar.cs.opencover.reportsPaths=coverage/**/*.xml
+            -Dsonar.cs.opencover.reportsPaths=coverage/coverage.cobertura.xml
 
   tag:
     runs-on: ubuntu-latest
@@ -83,10 +96,12 @@ jobs:
         uses: actions/checkout@v3
         with:
           fetch-depth: 0
+
       - name: Set up Git for tag push
         run: |
           git config user.name "github-actions"
           git config user.email "github-actions@github.com"
+
       - name: Bump Version and Create Tag
         id: tag
         run: |
